.TH IMAGE_PROCESS 6 Image_process\-0.1
.SH NAME
image_process \- fastest sharpening and edge detection program in the west!
.SH SYNOPSIS
.B ./Image_process
<input_png> <output_png> <effect> <num_threads>
.P
.BR ./Image_process " ..."
.SH DESCRIPTION
.B Image_process
An image processing tool to apply different effects on any png you have
.SH EFFECT
.TP
.B edge
 Detect edges in your image using sobel operator filters
.TP
.B sharpen
 Sharpen images using a standard filter
.SH AUTHOR
.B Marwan Abu Lebdeh


